<?php
use Illuminate\Support\Facades\Route;

Route::permanentRedirect("/o_nas", "/about/about_us");
Route::permanentRedirect("/history", "/about/our_history");
Route::permanentRedirect("/culture", "/about/corporate_culture");
Route::permanentRedirect("/socialnaja-otvetstvennost", "/about/social_responsibility");
Route::permanentRedirect("/certificates", "/about/certificates");
Route::permanentRedirect("/stroitelstvo", "/activity/construction");
Route::permanentRedirect("/energetika", "/activity/energy");
Route::permanentRedirect("/vypolnennye-proekty/", "/projects/completed_projects");
Route::permanentRedirect("/dejstvujushhie-proekty", "/projects/current_projects");
Route::permanentRedirect("/novosti-kompanii", "/media/company_news");
Route::permanentRedirect("/otraslevye-novosti/", "/media/industry_news");
Route::permanentRedirect("/galereja", "/media/gallery");
Route::permanentRedirect("/karera", "/career/career_in_tgem");
Route::permanentRedirect("/vakansii", "/career/vacancies");
Route::permanentRedirect("/kontakty", "/contacts/our_contacts");
Route::permanentRedirect("/reception", "/contacts/online_booking");


Route::permanentRedirect("/nurekskaya-ges", "/project/nurekskaya_ges/");
Route::permanentRedirect("/sangtudinskaya-ges-1", "/project/sangtudinskaya_ges_1");
Route::permanentRedirect("/hyatt-regency-hotel-i-bc-sozidanie", "/project/hyatt_regency_hotel_i_bts__sozidanie_");
Route::permanentRedirect("/elektrosnabzhenie-rudnika-zarnisor", "/project/elektrosnabzhenie_rudnika__zarnisor_");
Route::permanentRedirect("/mezhdunarodnyi-aeroport-dushanbe", "/project/mezhdunarodniy_aeroport_dushanbe");
Route::permanentRedirect("/ps-vahdat-110-10kv", "/project/ps__vahdat_110_10_kv_");
Route::permanentRedirect("/proekt-scada", "/project/proekt__scada_");
Route::permanentRedirect("/ps-ravshan-220-110-10-kv", "/project/ps_ravshan__220_110_10_kv");
Route::permanentRedirect("/regionalnyi-proekt-po-peredachi-elektroenergii-tadzhikistana", "/project/regionalyniy_proekt_po_peredachi_elektroenergii_tadzhikistana");
Route::permanentRedirect("/ps-korez-110-35-10kv", "/project/ps__korez__110_35_10_kv");
Route::permanentRedirect("/proekt-snizheniya-poter-elektroenergii-v-sogdiiskoi-oblasti", "/project/proekt_snizheniya_potery_elektroenergii_v_sogdiyskoy_oblasti");
Route::permanentRedirect("/krue-500-220-kv", "/project/krue_500_220_kv");
Route::permanentRedirect("/stroitelstvo-shkoly", "/project/stroitelystvo_shkoli");
Route::permanentRedirect("/ustanovka-transformatorov-na-ps-temurmalik", "/project/ps__temurmalik___110_10_kv");
Route::permanentRedirect("/proekt-askuje-hudzhand", "/project/proekt_askue_%28hudzhand%29");
Route::permanentRedirect("/ps-romit-110-10-kv", "/project/ps__romit__110_10_kv");
Route::permanentRedirect("/stroitelstvo-ljep-v-ir-afganistan", "/project/stroitelystvo_lep_v_ir_afganistan");
Route::permanentRedirect("/stroitelstvo-rogunskoj-gjes-lot-2", "/project/stroitelystvo_plotini_rogunskoy_ges._lot-2");
Route::permanentRedirect("/stroitelstvo-rogunskoj-gjes-lot-3", "/project/stroitelystvo_pravoberezhnih_sooruzheniy_rogunskoy_ges._lot-3");
Route::permanentRedirect("/casa-1000", "/project/casa_1000");
Route::permanentRedirect("/proekt-askuje-dushanbe", "/project/proekt_askue_%28dushanbe%29");
Route::permanentRedirect("/reabilitacija-kajrakkumskoj-gjes", "/project/reabilitatsiya_kayrakkumskoy_ges");
Route::permanentRedirect("/reabilitacija-nurekskoj-gjes", "/project/reabilitatsiya_nurekskoy_ges");
Route::permanentRedirect("/stroitelstvo-zavoda-po-proizvodstvu-jelektrooborudovanija", "/project/stroitelystvo_zavoda_po_proizvodstvu_elektrooborudovaniya");

Route::permanentRedirect("/podpisanie-investicionnogo-soglashenija-o-stroitelstve-i-jekspluatacii-predprijatija-po-proizvodstvu-jelektricheskogo-oborudovanija-v-gorode-dushanbe", "/news/podpisanie_investitsionnogo_soglasheniya_o_stroitelystve_i_ekspluatatsii_predpriyatiya_po_proizvodstvu_elektricheskogo_oborudovaniya_v_gorode_dushanbe");
Route::permanentRedirect("/otkrytie-podstancii-110-20-10-kv-i-ljep-04-kv-v-sele-romit-goroda-vahdat", "/news/otkritie_podstantsii_110_20_10_kv_i_lep_04_kv_v_sele_romit_goroda_vahdat");
Route::permanentRedirect("/sdacha-v-jekspluataciju-jelektricheskoj-podstancii-ravshan-220-110-35-10-kv-v-gorode-tursunzoda", "/news/sdacha_v_ekspluatatsiyu_elektricheskoy_podstantsii__ravshan__220_110_35_10_kv_v_gorode_tursunzoda");
Route::permanentRedirect("/podpisanie-kontrakta-po-proektu-upravlenija-vodnymi-resursami-v-bassejne-reki-pjandzh", "/news/podpisanie_kontrakta_po_proektu_upravleniya_vodnimi_resursami_v_basseyne_reki_pyandzh");
Route::permanentRedirect("/hod-realizacii-stroitelstva-jelektr", "/news/hod_realizatsii_stroitelystva_elektricheskih_setey_v_sele_romit");
Route::permanentRedirect("/oao-tgem-povtorno-okazala-gumanitarnuju-pomoshh-upravleniju-zdravoohraneniya-goroda-dushanbe/", "/news/oao__tgem__povtorno_okazala_gumanitarnuyu_pomoshby_upravleniyu_zdravoohraneniya_goroda_dushanbe");
Route::permanentRedirect("/upravleniju-zdravoohraneniya-dushanbe-predostavleno-20-tys-testov-dlya-opredeleniya-koronavirusa", "/upravleniyu_zdravoohraneniya_dushanbe_predostavleno_20_tis._testov_dlya_opredeleniya_koronavirusa");
Route::permanentRedirect("/podpisanie-kontrakta-po-proektu-rekonstrukciya-nurekskoi-ges", "/news/podpisanie_kontrakta_po_proektu__rekonstruktsiya_nurekskoy_ges_");
Route::permanentRedirect("/jica-sdast-v-ekspluataciju-2-podstancii-v-dushanbe", "/news/jica_sdast_v_ekspluatatsiyu_2_podstantsii_v_dushanbe");
Route::permanentRedirect("/otkrytie-ps-temurmalik", "/news/otkritie_ps__temurmalik_");
Route::permanentRedirect("/zapusk-proekta-jenergosnabzhenie-selskogo-dzhamoata-romit", "/news/ofitsialyniy_zapusk_proekta__energosnabzhenie_selyskogo_dzhamoata_romit_");
Route::permanentRedirect("/turnir-po-mini-futbolu-koinoti-nav-2018-2", "/news/turnir_po_mini-futbolu__koinoti_nav_2018_");
Route::permanentRedirect("/treningi-dlya-vypusknikov-ttu", "/news/treningi_dlya_vipusknikov_ttu");
Route::permanentRedirect("/ustanovka-transformatorov-na-ps-temurmalik", "/news/ps__temurmalik___110_10_kv");
Route::permanentRedirect("/v-hudzhande-dali-start-stroitelstvu-krupnoi-elektropodstancii", "/news/v_hudzhande_dali_start_stroitelystvu_krupnoy_elektropodstantsii");
Route::permanentRedirect("/otkrytie-shkoly-6-v-dushanbe", "/news/otkritie_shkoli_№6_v_dushanbe");
Route::permanentRedirect("/otkrytie-ps-110-10-vahdat-v-gorode-hudzhande", "/news/otkritie_ps_110_10__vahdat__v_gorode_hudzhande");
Route::permanentRedirect("/polnym-hodom-idet-stroitelstvo-ps-110-35-10-kv-korez", "/news/polnim_hodom_idet_stroitelystvo_ps_110_35_10_kv__korez_");
Route::permanentRedirect("/ceremoniya-vvoda-v-deistvie-vtorogo-agregata-rogunskoi-gidroelektrostancii", "/news/tseremoniya_vvoda_v_deystvie_vtorogo_agregata_rogunskoy_gidroelektrostantsii");
Route::permanentRedirect("/s-dnem-jenergetika", "/news/s_dnem_energetika_");

Route::permanentRedirect( "/otkrytie-podstancii-110-20-10-kv-i-ljep-04-kv-v-sele-romit-goroda-vahdat-2", "/media/gallery/otkritie_podstantsii_110_20_10_kv_i_lep_04_kv_v_sele_romit_goroda_vahdat");
Route::permanentRedirect("/sdacha-v-jekspluataciju-jelektricheskoj-podstancii-ravshan-220-110-35-10-kv-v-gorode-tursunzoda-2", "/media/gallery/sdacha_v_ekspluatatsiyu_elektricheskoy_podstantsii__ravshan__220_110_35_10_kv_v_gorode_tursunzoda");
Route::permanentRedirect("/podpisanie-kontrakta-po-proektu-upravlenija-vodnymi-resursami-v-bassejne-reki-pjandzh-2", "/media/gallery/podpisanie_kontrakta_po_proektu_upravleniya_vodnimi_resursami_v_basseyne_reki_pyandzh");
Route::permanentRedirect("/oao-tgem-povtorno-okazala-gumanitarnuju-pomoshh-upravleniju-zdravoohraneniya-goroda-dushanbe-2", "/media/gallery/oao__tgem__povtorno_okazala_gumanitarnuyu_pomoshby_upravleniyu_zdravoohraneniya_goroda_dushanbe");
Route::permanentRedirect("/upravleniju-zdravoohraneniya-dushanbe-predostavleno-20-tys-testov-dlya-opredeleniya-koronavirusa-2", "/media/gallery/upravleniyu_zdravoohraneniya_dushanbe_predostavleno_20_tis._testov_dlya_opredeleniya_koronavirusa");
Route::permanentRedirect("/podpisaniya-kontrakta-po-proektu-rekonstrukciya-nurekskoi-ges", "/media/gallery/podpisaniya_kontrakta_po_proektu__rekonstruktsiya_nurekskoy_ges_");
Route::permanentRedirect("/jica-sdast-v-ekspluataciju-2-podstancii-v-dushanbe-2", "/media/gallery/jica_sdast_v_ekspluatatsiyu_2_podstantsii_v_dushanbe");
Route::permanentRedirect("/ceremoniya-vvoda-v-deistvie-vtorogo-agregata-rogunskoi-gidroelektrostancii-2", "/media/gallery/tseremoniya_vvoda_v_deystvie_vtorogo_agregata_rogunskoy_gidroelektrostantsii");
Route::permanentRedirect("/otkrytie-ps-temurmalik-2", "/media/gallery/otkritie_ps__temurmalik_");
Route::permanentRedirect("/turnir-po-mini-futbolu-koinoti-nav-2018", "/media/gallery/turnir_po_mini-futbolu__koinoti_nav_2018_");
Route::permanentRedirect("/tehnika", "/media/gallery/tehnika");
Route::permanentRedirect("/trening-v-ttu", "/media/gallery/trening_v_ttu");
Route::permanentRedirect("/oficialnyi-zapusk-proekta-energosnabzhenie-selskogo-dzhamoata-romit", "/media/gallery/ofitsialyniy_zapusk_proekta__energosnabzhenie_selyskogo_dzhamoata_romit_");
Route::permanentRedirect("/otkrytie-ps-110-10-vahdat", "/media/gallery/otkritie_ps_110_10__vahdat_");
?>